spring:
  application:
    name: sysco-miniproject-dev

  datasource:
    url: jdbc:mysql://173.82.57.186:3307/sysco_min_pro_${spring.profiles.active}?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: adlonRo0t123
    driverclassname: com.mysql.cj.jdbc.Driver


  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update


server:
  port: 8080

bezkoder:
  app:
    jwtSecret: bezKoderSecretKey
    jwtExpirationMs: 86400000


#  ./gradlew sonarqube -D "sonar.projectKey=syscominiproject" -D "sonar.host.url=http://localhost:9000" -D "sonar.login=d8d4d71b79f6e83844ce54239d052afc2ba4e8fe"